# -*- coding: utf-8 -*-
"""kmeans-clustering_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FEcyFMdXs6JPfMIiMDSQnwqbdgdYkEh3
"""

from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

iris = load_iris()
X = iris.data

kmeans = KMeans(n_clusters=3, random_state = 2)
kmeans.fit(X)

kmeans.labels_

kmeans.inertia_

kmeans.cluster_centers_

kmeans.predict(X[:1,:])

y = iris.target

from sklearn.metrics import accuracy_score
accuarcy = accuracy_score(y, kmeans.labels_)*100
print('kmeans accuarcy: {}%'.format(accuarcy.round(2)))

inertia = []
for k in range (1,10):
  kmeans = KMeans(n_clusters=k)
  kmeans.fit(X)
  inertia.append(kmeans.inertia_)

plt.xlabel('K_Clusters')
plt.ylabel('SSE Inertia')
plt.plot(range(1,10), inertia)
plt.show();

