# -*- coding: utf-8 -*-
"""kmeans-clustering_accuarcy_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14IzWim85jHS9o_bcs3D5jZaJPB6PMNhy
"""

from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

iris = load_iris()
X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1)

kmeans = KMeans(n_clusters=3, random_state = 2)
kmeans.fit(X_train)

kmeans.labels_

y_train

kmeans.inertia_

kmeans.cluster_centers_

y_pred = kmeans.predict(X_test)

y_pred

from sklearn.metrics import accuracy_score
accuarcy = accuracy_score(y_test, y_pred)*100
print('kmeans accuarcy: {}%'.format(accuarcy.round(2)))

